apiVersion: v1
kind: Service
metadata:
  name: chromadb-service
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: chromadb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chromadb
spec:
  serviceName: "chromadb-service"
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
        - name: chromadb
          image: localhost/af-chroma:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: chroma-storage
              mountPath: /chroma/chroma
  volumeClaimTemplates:
    - metadata:
        name: chroma-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi